# Generated by Django 4.1.3 on 2022-11-26 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('id_courier', models.IntegerField()),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('number_of_items', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_waybill', models.IntegerField()),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('destination_mobile', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waybill', to='courier.courier')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waybill', to='courier.shipment')),
            ],
        ),
    ]
