# Generated by Django 4.1.3 on 2022-11-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_courier', models.IntegerField()),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='shipment_id',
            new_name='id_shipment',
        ),
        migrations.RemoveField(
            model_name='waybill',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='waybill',
            name='shipment',
        ),
        migrations.DeleteModel(
            name='Courier',
        ),
        migrations.AddField(
            model_name='courierman',
            name='waybill',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courier.waybill'),
        ),
    ]
