# Generated by Django 4.1.3 on 2022-11-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0004_alter_courierman_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierman',
            name='username',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courierman',
            name='last_name',
            field=models.CharField(max_length=15),
        ),
    ]
