# Generated by Django 4.1.3 on 2022-11-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0005_courierman_username_alter_courierman_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierman',
            name='last_name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
