# Generated by Django 4.1.3 on 2022-11-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0006_alter_courierman_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierman',
            name='last_name',
            field=models.CharField(default='sss', max_length=15),
            preserve_default=False,
        ),
    ]
