# Generated by Django 4.1.3 on 2022-11-27 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0007_alter_courierman_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courierman',
            name='last_name',
        ),
    ]
