# Generated by Django 4.1.3 on 2022-11-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0010_remove_courierman_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierman',
            name='last_name',
            field=models.CharField(max_length=15),
        ),
    ]
