# Generated by Django 4.1.3 on 2022-11-27 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0013_remove_courierman_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courierman',
            name='last_name',
        ),
    ]
