# Generated by Django 4.1.3 on 2022-11-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0014_remove_courierman_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierman',
            name='last_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='courierman',
            name='phone_number',
            field=models.CharField(default='ddd', max_length=20),
            preserve_default=False,
        ),
    ]
