# Generated by Django 4.1.3 on 2022-11-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0015_courierman_last_name_courierman_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierman',
            name='id_courier',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courierman',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='courierman',
            name='last_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='courierman',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
