# Generated by Django 4.1.3 on 2022-11-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0018_remove_waybill_destination_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='destination',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='id_waybill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
