# Generated by Django 4.1.3 on 2022-11-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0019_alter_waybill_destination_alter_waybill_id_waybill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
