# Generated by Django 4.1.3 on 2022-11-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0020_alter_waybill_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
